import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import ym from 'react-yandex-metrika';
import {YMInitializer} from 'react-yandex-metrika';
import { Router } from 'next/router';

Router.events.on("routeChangeComplete",(url:string)=>{
  if (typeof window !== "undefined"){
    ym("hit",url);
  }
});

function MyApp({ Component, pageProps,router }:AppProps):JSX.Element {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://mc.yandex.ru" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Display:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <meta property="og:url" content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath} />
      </Head>
      <YMInitializer accounts={[]} options={{webvisor:true,defe:true}} version="2" />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
